import time
import os
import math
from core.drone_interface import MavlinkDrone
from core.vision_system import ColorDetector

SYSTEM_ADDR = "udp:127.0.0.1:14561" # Assuming Mule uses second UDP port on GCS
FLIGHT_ALTITUDE = 15.0
DROP_ALTITUDE = 6.0 # 20 feet
SERVO_INSTANCE = 9

class MuleMission:
    def __init__(self):
        print("="*50)
        print("MULE (HEXACOPTER) MISSION INITIALIZING")
        print("="*50)
        
        self.drone = MavlinkDrone(SYSTEM_ADDR)
        if not self.drone.connected:
             print("-- [MULE] Failed to connect to GCS Hub.")
             return
             
        self.targets = []
        self.current_servo_angle = 0.0
        self.is_first_drop = True

    def rotate_revolver_dropper(self):
        """Actuates the 10-slot revolver dropping mechanism."""
        if self.is_first_drop:
            increment = 10.0
            self.is_first_drop = False
        else:
            increment = 18.0
            
        self.current_servo_angle += increment
        if self.current_servo_angle > 180.0:
            print("-- [MULE] Warning: Revolver capacity reached.")
            self.current_servo_angle = 180.0

        # Map 0-180 deg to 500-2500 PWM
        pwm = int(500 + (self.current_servo_angle / 180.0) * 2000)
        print(f"   [SERVO] Rotating to {self.current_servo_angle} deg (PWM: {pwm})")
        
        # Send 3 times for reliability
        for _ in range(3):
            self.drone.set_servo(SERVO_INSTANCE, pwm)
            time.sleep(0.05)
        time.sleep(1.0) # Wait for mechanical action

    def monitor_target_feed(self, filename="detected_targets.txt"):
        """Monitors the text file for new coordinates generated by the Scout."""
        print("-- [MULE] Waiting for target data from Scout...")
        last_mtime = 0
        processed_lines = 0
        
        while self.drone.running:
            if not os.path.exists(filename):
                time.sleep(1)
                continue
                
            mtime = os.path.getmtime(filename)
            if mtime > last_mtime:
                last_mtime = mtime
                with open(filename, 'r') as f:
                    lines = f.readlines()
                    
                for i in range(processed_lines, len(lines)):
                    line = lines[i].strip()
                    if line == "MISSION_COMPLETE":
                        print("-- [MULE] Scout mission complete. All targets received.")
                        return
                    elif line and "LAT" not in line:
                        parts = line.split(',')
                        if len(parts) >= 2:
                            lat, lon = float(parts[0]), float(parts[1])
                            self.targets.append((lat, lon))
                            print(f"-- [MULE] New Target Added: {lat:.6f}, {lon:.6f}")
                processed_lines = len(lines)
            time.sleep(2)

    def execute_deliveries(self):
        """Executes the delivery sequence for all targets."""
        if not self.targets:
            print("-- [MULE] No targets acquired. Standing down.")
            return

        print(f"-- [MULE] Commencing Delivery Sequence for {len(self.targets)} targets.")
        
        self.drone.wait_gps()
        self.drone.set_mode("GUIDED")
        time.sleep(1)
        if not self.drone.arm(): return
        
        self.drone.takeoff(FLIGHT_ALTITUDE)
        time.sleep(10)
        
        for idx, (lat, lon) in enumerate(self.targets):
            print(f"\n-- [MULE] Navigating to Target {idx+1}/{len(self.targets)}")
            
            # Send Global Int waypoint command (simplified from drone_interface for targeted GOTO)
            self.drone.master.mav.set_position_target_global_int_send(
                0, self.drone.master.target_system, self.drone.master.target_component,
                6, # MAV_FRAME_GLOBAL_RELATIVE_ALT_INT
                0b0000111111111000, # Position only
                int(lat * 1e7), int(lon * 1e7), DROP_ALTITUDE,
                0,0,0, 0,0,0, 0,0
            )
            
            # Wait to reach destination (Simplified check)
            start_time = time.time()
            reached = False
            while time.time() - start_time < 60: # 60s timeout per target
                state, _, _, _ = self.drone.get_state()
                # Rough distance check
                dist = ((state.lat - lat)**2 + (state.lon - lon)**2)**0.5 * 111132
                if dist < 2.0 and abs(state.alt - DROP_ALTITUDE) < 1.0:
                    print("   [MULE] Arrived at drop zone (Zone A).")
                    reached = True
                    break
                time.sleep(1)
                
            if reached:
                # Add Visual Alignment logic here if needed, 
                # for now, assume GPS accuracy is sufficient or visual servoing is handled.
                print("   [MULE] Executing Payload Drop...")
                self.rotate_revolver_dropper()
                print("   [MULE] Drop confirmed.")
            else:
                print("   [MULE] Navigation timeout. Proceeding to next.")

        print("\n-- [MULE] All deliveries complete. Returning to launch.")
        self.drone.return_to_launch()
        time.sleep(5)
        self.drone.close()

if __name__ == "__main__":
    mission = MuleMission()
    mission.monitor_target_feed()
    mission.execute_deliveries()
